version: "3.8"
services:
  webserver:
    build: .
    restart: always
    command: > 
      bash -c "airflow db reset -y && 
      airflow db upgrade &&
      airflow db init && 
      airflow users create --username airflow --firstname Airflow --lastname User --role Admin --email airflow@example.com --password airflow && 
      airflow webserver"
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - 8080:8080
    depends_on:
      - db
      - kafka
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor

  scheduler:
    build: .
    restart: always
    command: airflow scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
    depends_on:
      - db
      - kafka
      - webserver
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - TZ=America/Lima

  zookeeper:
    image: zookeeper:3.8.1
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: bitnami/kafka:3.3.2-debian-11-r58
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CREATE_TOPICS=topic1:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - ALLOW_PLAINTEXT_LISTENER=yes
